site_name: Replace and Route
# site_url: https://gitlab.sh.nextgenwaterprediction.com/NGWPC/fim-s/rnr/
site_author: Tadd Bindas

# Repository
repo_name: NOAA-OWP/Hydrovis
repo_url: https://github.com/NOAA-OWP/hydrovis

# Copyright
copyright: Copyright &copy; 2024 Raytheon 

# Configuration
theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: black
      accent: red

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: black
      accent: red
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.top
    - navigation.instant
    - navigation.instant.progress
    - toc.follow
    - toc.integrate 
    - search.suggest
plugins:
  search: null
  mkdocstrings:
    handlers:
      python:
        paths: [src]
nav:
  - Home: index.md
  - Getting started:
    - getting_started/index.md
  - User Guide:
    - user_guide/index.md
    - Publisher: user_guide/publisher.md
  - Reference:
    - reference/index.md
    - Publisher: 
      - Client: reference/publisher/client.md
      - Routes: reference/publisher/routes.md
      - Services: reference/publisher/services.md
