name: hand-fim
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - awslambdaric
  - numpy
  - sqlalchemy<2.0
  - geoalchemy2
  - psycopg2
  - rasterio>=1.3.0,<1.4.0
  - geopandas
  - pandas>=2.0
  - fsspec
  - s3fs