repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        files: ^Source/
      - id: end-of-file-fixer
        files: ^Source/
      - id: check-yaml
        files: ^Source/
      - id: debug-statements
        files: ^Source/

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.11.9
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix]
      # Run the formatter.
      - id: ruff-format

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.7.3
    hooks:
      - id: uv-lock

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
