FROM rockylinux:9.3
RUN yum install -y epel-release
RUN yum install -y git cmake

COPY --from=ghcr.io/astral-sh/uv:0.7.3 /uv /uvx /bin/

# Use UV to install Python 3.11
RUN uv python install 3.11

# Clone the repository
RUN git clone https://github.com/NGWPC/t-route.git
WORKDIR "/t-route/"
RUN git checkout pi_6

# Create a directory for local packages
RUN mkdir -p /app/wheels

# Copy the pre-built wheel from the build context
COPY dist/icefabric_tools-*.whl /app/wheels/
COPY dist/icefabric_manage-*whl /app/wheels/

# Create venv and set environment to use it
RUN uv venv
ENV PATH="/app/.venv/bin:$PATH"

# Install the troute-rnr package specifically
WORKDIR "/t-route/src/troute-rnr"
RUN uv pip install /app/wheels/icefabric_tools-*.whl
RUN uv pip install /app/wheels/icefabric_manage-*.whl
RUN uv pip install -e .
