name: ripple_processing
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - awslambdaric
  - fsspec
  - s3fs
  - loguru=0.7.2
  - geopandas
  - sqlalchemy
  - psycopg2
  - shapely
  - numpy
  - pandas
  - rasterio
  - requests
